### ISSUE TITLE
Only opens software update pane under macOS Ventura 13.2

### ISSUE THREAD

**Issue by notasocialist** [xirianlight/openToMoreInfo#6]
Under macOS 13.2 I noticed this script only opens System Preferences / Software Update.  It does not click through to more info and install the update as it does under macOS 11.x and 12.x.

**Comment by HowardGMac** [comment]
For what its worth, in my testing with macOS 13.5 Apple has still NOT fixed the accessibility linking in System Settings to the "More Info..." link/button like that needed for this to start working  properly again.

**Comment by xirianlight** [comment]
The latest build addresses this as best we can since Apple indeed has not yet made the "More Info" button an interactive Accessibility target as of 14.2 and 13.6.1. If they ever change this, I'll update the script to detect minor macOS versions to be able to hit the button at least in some operating systems.
